---
apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: debezium-connect-postgres
      context: debezium-connect-postgres
    - image: headband
      context: headband
    - image: dispatcher
      context: dispatcher
  local:
    concurrency: 2
manifests:
  rawYaml:
    - k8s/postgres.yaml
    - k8s/kafka.yaml
    - k8s/debezium.yaml
    - k8s/headband.yaml
    - k8s/dispatcher.yaml
deploy:
  kubectl: {}
  helm:
    releases:
      - name: strimzi-cluster-operator
        remoteChart: oci://quay.io/strimzi-helm/strimzi-kafka-operator
        version: "0.42.0"
        # namespace: kafka
        # createNamespace: true
