---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  labels:
    app.kubernetes.io/name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dispatcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dispatcher
    spec:
      containers:
        - name: dispatcher
          image: dispatcher
