---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headband
  labels:
    app.kubernetes.io/name: headband
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: headband
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headband
    spec:
      containers:
        - name: headband
          image: headband
