# Based upon: https://debezium.io/documentation/reference/stable/operations/kubernetes.html#_deploying_apache_kafka
# For other examples see: https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/kafka/
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: debezium-cluster
spec:
  kafka:
    version: 3.7.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: ephemeral
      size: 10Gi
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      # inter.broker.protocol.version: "3.7"
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
      size: 10Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}